-- Canonical GED schema for patient_documents
-- Run inside the primary database (Supabase / Postgres)

begin;

create extension if not exists "pgcrypto";

create table if not exists public.patient_documents (
    id uuid primary key default gen_random_uuid(),
    patient_id uuid not null references public.patients(id) on delete cascade,
    title text not null,
    description text,
    external_ref text,
    tags text[],

    -- Classification / security
    domain text not null default 'Administrativo',
    category text not null,
    subcategory text,
    origin_module text not null default 'Ficha_Documentos',
    document_status text not null default 'Ativo',
    confidential boolean not null default false,
    clinical_visible boolean not null default true,
    admin_fin_visible boolean not null default true,
    min_access_role text,

    -- Storage metadata
    storage_provider text not null default 'Supabase',
    storage_path text not null,
    original_file_name text not null,
    file_path text not null,
    file_size_bytes bigint not null,
    mime_type text not null,
    extension text not null,
    file_hash text,

    -- Version/lifecycle
    version integer not null default 1,
    previous_document_id uuid references public.patient_documents(id) on delete set null,
    expires_at date,
    is_verified boolean not null default false,
    verified_at timestamptz,
    verified_by uuid references auth.users(id) on delete set null,
    deleted_at timestamptz,
    deleted_by uuid references auth.users(id) on delete set null,

    -- Cross-module links
    admin_contract_id text,
    finance_entry_id uuid references public.financial_records(id) on delete set null,
    clinical_visit_id uuid,
    clinical_evolution_id uuid,
    prescription_id uuid,
    related_object_id uuid,

    -- Signature metadata
    signature_type text not null default 'Nenhuma',
    signature_date timestamptz,
    signature_summary text,
    external_signature_id text,

    -- Audit
    uploaded_at timestamptz not null default now(),
    uploaded_by uuid references auth.users(id) on delete set null,
    updated_at timestamptz default now(),
    updated_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create table if not exists public.patient_document_logs (
    id bigint generated by default as identity primary key,
    tenant_id uuid not null,
    patient_id uuid not null references public.patients(id) on delete cascade,
    document_id uuid not null references public.patient_documents(id) on delete cascade,
    user_id uuid references auth.users(id) on delete set null,
    action text not null,
    happened_at timestamptz not null default now(),
    document_category text,
    document_domain text,
    document_origin text,
    document_status text,
    document_version integer,
    details jsonb
);

-- Canonical indexes referenced by GED panel filters
create index if not exists idx_patient_documents_category on public.patient_documents (category);
create index if not exists idx_patient_documents_domain on public.patient_documents (domain);
create index if not exists idx_patient_documents_status on public.patient_documents (document_status);
create index if not exists idx_patient_documents_origin on public.patient_documents (origin_module);
create index if not exists idx_patient_documents_created on public.patient_documents (created_at desc);
create index if not exists idx_patient_documents_patient_status on public.patient_documents (patient_id, document_status);
create index if not exists idx_patient_documents_patient_cat_dom on public.patient_documents (patient_id, category, domain);
create index if not exists idx_patient_documents_patient_created_at on public.patient_documents (patient_id, created_at desc);
create index if not exists idx_patient_documents_tags_gin on public.patient_documents using gin (tags);

-- Covering index required by caregiver lookup
create index if not exists idx_care_team_members_user_patient_dates
  on public.care_team_members (user_profile_id, patient_id, start_date, end_date);

-- RLS -----------------------------------------------------------------------
alter table public.patient_documents enable row level security;

create or replace view public.current_care_team as
select ctm.*, up.auth_user_id
from public.care_team_members ctm
join public.user_profiles up on up.id = ctm.user_profile_id;

create or replace function public.can_access_patient_document(doc public.patient_documents)
returns boolean
language sql
stable
as $$
    select
      doc.admin_fin_visible
      or (
        doc.clinical_visible
        and exists (
          select 1
          from public.current_care_team c
          where c.patient_id = doc.patient_id
            and c.auth_user_id = auth.uid()
            and coalesce(c.start_date, now() - interval '100 years') <= now()
            and coalesce(c.end_date, now() + interval '100 years') >= now()
        )
      );
$$;

drop policy if exists patient_documents_select_authenticated on public.patient_documents;
drop policy if exists patient_documents_insert_authenticated on public.patient_documents;
drop policy if exists patient_documents_update_authenticated on public.patient_documents;

create policy patient_documents_select_authenticated on public.patient_documents
for select
using (public.can_access_patient_document(patient_documents));

create policy patient_documents_insert_authenticated on public.patient_documents
for insert
with check (public.can_access_patient_document(patient_documents));

create policy patient_documents_update_authenticated on public.patient_documents
for update
using (public.can_access_patient_document(patient_documents))
with check (public.can_access_patient_document(patient_documents));

commit;
