import { z } from "zod";

export const RelatedPersonZ = z.object({
  id: z.string().uuid().optional(),
  patientId: z.string().uuid(),
  tenantId: z.string().uuid().optional(),
  fullName: z.string().min(2, "Nome obrigatório"),
  relation: z.string().optional(),
  priorityOrder: z.number().optional(),
  phonePrimary: z.string().optional(),
  phoneSecondary: z.string().optional(),
  isWhatsapp: z.boolean().default(false),
  email: z.string().email().optional(),
  isLegalGuardian: z.boolean().default(false),
  isFinancialResponsible: z.boolean().default(false),
  isEmergencyContact: z.boolean().default(false),
  canAccessRecords: z.boolean().default(false),
  canAuthorizeProcedures: z.boolean().default(false),
  canAuthorizeFinancial: z.boolean().default(false),
  livesWithPatient: z.enum(["sim", "nao", "visita_frequente", "visita_eventual"]).optional(),
  hasKeys: z.boolean().default(false),
  contactWindow: z.string().optional(),
  preferredContact: z.string().optional(),
  receiveUpdates: z.boolean().default(false),
  receiveAdmin: z.boolean().default(false),
  optOutMarketing: z.boolean().default(false),
  notes: z.string().optional(),
  cpf: z.string().optional(),
  birthDate: z.string().optional(),
  rg: z.string().optional(),
  rgIssuer: z.string().optional(),
  rgState: z.string().optional(),
  addressStreet: z.string().optional(),
  addressCity: z.string().optional(),
  addressState: z.string().optional(),
});

export const CareTeamMemberZ = z.object({
  id: z.string().uuid().optional(),
  patientId: z.string().uuid(),
  tenantId: z.string().uuid().optional(),
  professionalId: z.string().uuid(),
  role: z.string().min(2, "Função obrigatória"),
  professionalCategory: z.string().optional(),
  caseRole: z.string().optional(),
  regime: z.enum(["Fixo", "Plantão", "Sobreaviso", "Outro"]).default("Plantão"),
  status: z.enum(["active", "inactive", "away", "closed"]).default("active"),
  employmentType: z.string().optional(),
  shiftSummary: z.string().optional(),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  contactPhone: z.string().optional(),
  contactEmail: z.string().optional(),
  isTechnicalResponsible: z.boolean().default(false),
  isFamilyFocalPoint: z.boolean().default(false),
  isPrimary: z.boolean().default(false),
  notes: z.string().optional(),
});

export type RelatedPersonForm = z.infer<typeof RelatedPersonZ>;
export type CareTeamMemberForm = z.infer<typeof CareTeamMemberZ>;
