import { z } from "zod";

export const PatientAdminInfoZ = z.object({
  patient_id: z.string().uuid(),
  tenant_id: z.string().uuid(),

  // Contrato & vigência
  status: z.string().optional(),
  status_reason: z.string().optional(),
  status_changed_at: z.string().datetime().optional(),
  admissionType: z.enum(["Internacao_Domiciliar", "Cuidados_Paliativos", "Assistencia_Ventilatoria", "Reabilitacao", "Procedimento_Pontual", "Outro"], { required_error: "Tipo de admissão obrigatório" }),
  demandOrigin: z.enum(["Particular", "OperadoraSaude", "SUS", "Empresa", "Judicial", "Outro"]).optional(),
  demandOriginDescription: z.string().optional(),
  primaryPayerType: z.enum(["Operadora", "PessoaFisica", "Empresa", "OrgaoPublico", "Outro"]),
  startDate: z.string().min(1, "Data de admissão obrigatória"),
  endDate: z.string().optional(),
  effectiveDischargeDate: z.string().optional(),
  contractStartDate: z.string().optional(),
  contractEndDate: z.string().optional(),
  renewalType: z.enum(["Automatica", "Periodo_Fixo", "Por_Laudo", "Judicial"]).optional(),
  contractId: z.string().optional(),
  externalContractId: z.string().optional(),
  authorizationNumber: z.string().optional(),
  judicialCaseNumber: z.string().optional(),
  officialLetterNumber: z.string().optional(),
  contractStatusReason: z.string().optional(),
  adminNotes: z.string().optional(),
  costCenterId: z.string().optional(),
  erpCaseCode: z.string().optional(),
  contractCategory: z.enum(["Particular_Premium", "Convenio_Padrao", "Judicial", "SUS", "Cortesia"]).optional(),
  acquisitionChannel: z.string().optional(),
  servicePackageName: z.string().optional(),
  servicePackageDescription: z.string().optional(),
  contractStatusEnum: z.enum(["Proposta", "Em_Implantacao", "Ativo", "Suspenso", "Encerrado", "Cancelado", "Recusado"]).optional(),

  // Responsáveis
  supervisorId: z.string().optional(),
  escalistaId: z.string().optional(),
  commercialResponsibleId: z.string().optional(),
  contractManagerId: z.string().optional(),
  payerAdminContactId: z.string().uuid().optional(),
  payerAdminContactDescription: z.string().optional(),
  primaryPayerDescription: z.string().optional(),
  primaryPayerRelatedPersonId: z.string().uuid().optional(),
  primaryPayerLegalEntityId: z.string().optional(),

  // Escala
  frequency: z.string().optional(),
  scaleModel: z.enum(["12x36", "24x48", "Visita", "Plantao_Avulso", "Semanal_5x2", "Outro"]).optional(),
  scaleMode: z.string().optional(),
  shiftModality: z.enum(["Continuo", "Alternado", "Sob_Aviso"]).optional(),
  baseProfessionalCategory: z.enum(["Medico", "Enfermeiro", "TecEnf", "Fisio", "Fono", "Nutri", "Psicologo", "Terapeuta", "Cuidador", "Outro"]).optional(),
  quantityPerShift: z.coerce.number().optional(),
  weeklyHoursExpected: z.coerce.number().optional(),
  dayShiftStart: z.string().optional(),
  nightShiftStart: z.string().optional(),
  dayShiftEnd: z.string().optional(),
  nightShiftEnd: z.string().optional(),
  referenceLocationId: z.string().uuid().optional(),
  includesWeekends: z.boolean().optional(),
  holidayRule: z.string().optional(),
  autoGenerateScale: z.boolean().optional(),
  scaleRuleStartDate: z.string().optional(),
  scaleRuleEndDate: z.string().optional(),
  scaleNotes: z.string().max(500).optional(),

  // Checklist
  chkContractOk: z.boolean().default(false),
  chkContractAt: z.string().optional(),
  chkContractBy: z.string().optional(),
  chkConsentOk: z.boolean().default(false),
  chkConsentAt: z.string().optional(),
  chkConsentBy: z.string().optional(),
  chkMedicalReportOk: z.boolean().default(false),
  chkMedicalReportAt: z.string().optional(),
  chkMedicalReportBy: z.string().optional(),
  chkLegalDocsOk: z.boolean().default(false),
  chkFinancialDocsOk: z.boolean().default(false),
  chkJudicialOk: z.boolean().default(false),
  chkAddressProofOk: z.boolean().default(false),
  chkLegalGuardianDocsOk: z.boolean().default(false),
  chkFinancialResponsibleDocsOk: z.boolean().default(false),
  chkOtherDocsOk: z.boolean().default(false),
  chkOtherDocsDesc: z.string().optional(),
  chkContractDocId: z.string().uuid().optional(),
  chkConsentDocId: z.string().uuid().optional(),
  chkMedicalReportDocId: z.string().uuid().optional(),
  chkAddressProofDocId: z.string().uuid().optional(),
  chkLegalDocsDocId: z.string().uuid().optional(),
  chkFinancialDocsDocId: z.string().uuid().optional(),
  chkJudicialDocId: z.string().uuid().optional(),
  checklistComplete: z.boolean().default(false),
  checklistNotes: z.string().optional(),
  checklistNotesDetailed: z.string().optional(),
  chkAddressProofAt: z.string().optional(),
  chkAddressProofBy: z.string().optional(),
  chkLegalGuardianDocsAt: z.string().optional(),
  chkLegalGuardianDocsBy: z.string().optional(),
  chkFinancialResponsibleDocsAt: z.string().optional(),
  chkFinancialResponsibleDocsBy: z.string().optional(),
  chkOtherDocsAt: z.string().optional(),
  chkOtherDocsBy: z.string().optional(),
  chkJudicialAt: z.string().optional(),
  chkJudicialBy: z.string().optional(),
}).superRefine((data, ctx) => {
  if (data.status === "Encerrado" && !data.effectiveDischargeDate) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: "Data de alta efetiva obrigatória para status Encerrado", path: ["effectiveDischargeDate"] });
  }
});

export type PatientAdminInfoForm = z.infer<typeof PatientAdminInfoZ>;
